{
 "title": "Kubernetes Pod Metrics",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   },
   {
    "name": "Pod_ip",
    "query": {
     "query": "label_values(kube_pod_info{pod=~\"$Pod.*$\"}, pod_ip)"
    }
   },
   { "name": "phase", "query": { "query": "label_values(phase)" } },
   {
    "name": "container",
    "query": {
     "query": "label_values(kube_pod_container_info, container)"
    }
   },
   {
    "name": "Pod",
    "query": {
     "query": "label_values(kube_pod_container_resource_limits{resource=\"cpu\", namespace=~\"^(catalyst-prod-backend|catalyst-prod-frontend)$\", pod!~\"^(worker|redis|rabbitmq|nats).*\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Network I/O pressure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Network I/O pressure",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{pod=~\"^$Pod$\"}[10m])) by (pod)\n",
       "legendFormat": "Received"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{pod=~\"^$Pod$\"}[10m])) by (pod)",
       "legendFormat": "Sent"
      }
     ]
    }
   ]
  },
  {
   "title": "Total usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pod Memory Usage (last 10 minutes)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_memory_working_set_bytes{pod=~\"^$Pod$\"}[10m])) * 100 / sum(kube_pod_container_resource_limits{resource=\"memory\", pod=~\"^$Pod$\"})"
    }
   ]
  },
  {
   "title": "Pod IP Address",
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 2 },
   "options": { "content": "                $Pod_ip" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pod CPU Usage (last 10 minutes)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod=~\"^$Pod$\"}[10m])) * 100 / sum(kube_pod_container_resource_limits{resource=\"cpu\", pod=~\"^$Pod$\"})\n"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 5 },
   "options": { "content": "                  $phase" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (rate(container_memory_working_set_bytes{pod=~\"^$Pod$\"}[10m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_limits{pod=~\"^$Pod$\", resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod=~\"^$Pod$\"}[10m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_limits{resource=\"cpu\", pod=~\"^$Pod$\"})"
    }
   ]
  },
  {
   "title": "All processes CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "All Processes CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum by (pod) (kube_pod_container_resource_limits{resource=\"cpu\", namespace=~\"^(catalyst-prod-backend|catalyst-prod-frontend)$\", pod!~\"^(worker|redis|rabbitmq|nats).*\"}) ) ",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "All processes Pods memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "All Processes Pods Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"^$Pod$\"})",
     "legendFormat": "{{ io_kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "All processes Pods network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "All Processes Pods Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{pod=~\"^$Pod$\"}[10m])) by (pod)",
     "legendFormat": "-> {{ io_kubernetes_pod_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{pod=~\"^$Pod$\"}[1m])) by (pod)",
     "legendFormat": "<- {{ io_kubernetes_pod_name }}"
    }
   ]
  }
 ]
}