apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alerting
  namespace: monitoring
data:
  rules.yaml: |-
    apiVersion: 1
    groups:
      - orgId: 1
        name: alerting
        folder: alerting
        interval: 10s
        rules:
          - uid: a1b2c3
            title: pod_crashloop
            condition: C
            data:
              - refId: A
                relativeTimeRange:
                  from: 300
                  to: 0
                datasourceUid: PBFA97CFB590B2093
                model:
                  editorMode: code
                  expr: increase(kube_pod_container_status_restarts_total[5m]) > 2
                  hide: false
                  intervalMs: 1000
                  legendFormat: __auto
                  maxDataPoints: 43200
                  range: true
                  refId: A
              - refId: B
                relativeTimeRange:
                  from: 300
                  to: 0
                datasourceUid: __expr__
                model:
                  conditions:
                      - evaluator:
                          params:
                              - 0
                              - 0
                          type: gt
                        operator:
                          type: and
                        query:
                          params: []
                        reducer:
                          params: []
                          type: avg
                        type: query
                  datasource:
                      name: Expression
                      type: __expr__
                      uid: __expr__
                  expression: A
                  intervalMs: 1000
                  maxDataPoints: 43200
                  reducer: mean
                  refId: B
                  settings:
                      mode: ""
                  type: reduce
              - refId: C
                datasourceUid: __expr__
                model:
                  conditions:
                      - evaluator:
                          params:
                              - 0
                              - 0
                          type: gt
                        operator:
                          type: and
                        query:
                          params: []
                        reducer:
                          params: []
                          type: avg
                        type: query
                  datasource:
                      name: Expression
                      type: __expr__
                      uid: __expr__
                  expression: $B > 0
                  hide: false
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: C
                  type: math
            noDataState: OK
            execErrState: Alerting
            for: 10s
            annotations:
              description: |-
                  Pod has been in crashloop state for longer than 5 minutes.  Namespace: {{ "{{" }}  $labels.namespace }}
                  Pod: {{ "{{" }} $labels.pod }}
              summary: Kubernetes Pod is crashlooping
            labels:
              pod_status: crashloop
            isPaused: false
      - orgId: 1
        name: alerting
        folder: alerting
        interval: 10s
        rules:
          - uid: b19ea9f8-c0f3-4e6c-ab0c-b99402710fcb
            title: pod_health
            condition: C
            data:
              - refId: A
                relativeTimeRange:
                  from: 300
                  to: 0
                datasourceUid: PBFA97CFB590B2093
                model:
                  editorMode: code
                  expr: (kube_pod_status_phase{phase=~"Pending|Unknown|Failed"}) > 0
                  hide: false
                  intervalMs: 1000
                  legendFormat: __auto
                  maxDataPoints: 43200
                  range: true
                  refId: A
              - refId: B
                relativeTimeRange:
                  from: 300
                  to: 0
                datasourceUid: __expr__
                model:
                  conditions:
                      - evaluator:
                          params: []
                          type: gt
                        operator:
                          type: and
                        query:
                          params:
                              - B
                        reducer:
                          params: []
                          type: last
                        type: query
                  datasource:
                      type: __expr__
                      uid: __expr__
                  expression: A
                  hide: false
                  intervalMs: 1000
                  maxDataPoints: 43200
                  reducer: last
                  refId: B
                  type: reduce
              - refId: C
                relativeTimeRange:
                  from: 300
                  to: 0
                datasourceUid: __expr__
                model:
                  conditions:
                      - evaluator:
                          params:
                              - 0
                              - 0
                          type: gt
                        operator:
                          type: and
                        query:
                          params: []
                        reducer:
                          params: []
                          type: avg
                        type: query
                  datasource:
                      name: Expression
                      type: __expr__
                      uid: __expr__
                  expression: $B > 0
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: C
                  type: math
            noDataState: OK
            execErrState: Alerting
            for: 10s
            annotations:
              description: |-
                  Pod has been in a non-ready state for longer than 5 minutes. Namespace: {{ "{{" }} $labels.namespace }}
                  Pod: {{ "{{" }} $labels.pod }}
              summary: Kubernetes Pod not healthy.
            labels:
              pod_status: unhealthy
            isPaused: false    
      - orgId: 1
        name: alerting
        folder: alerting
        interval: 10s
        rules:
          - uid: a4deda02-ccb1-4000-86f0-0f3544818e05
            title: pod_probes
            condition: C
            data:
              - refId: A
                relativeTimeRange:
                  from: 600
                  to: 0
                datasourceUid: PBFA97CFB590B2093
                model:
                  editorMode: code
                  expr: ( kube_pod_info{created_by_kind!="Job"} AND ON (pod, namespace) kube_pod_status_ready{condition="false"} == 1) > 0
                  hide: false
                  intervalMs: 1000
                  legendFormat: __auto
                  maxDataPoints: 43200
                  range: true
                  refId: A
              - refId: B
                relativeTimeRange:
                  from: 600
                  to: 0
                datasourceUid: __expr__
                model:
                  conditions:
                      - evaluator:
                          params: []
                          type: gt
                        operator:
                          type: and
                        query:
                          params:
                              - B
                        reducer:
                          params: []
                          type: last
                        type: query
                  datasource:
                      type: __expr__
                      uid: __expr__
                  expression: A
                  hide: false
                  intervalMs: 1000
                  maxDataPoints: 43200
                  reducer: mean
                  refId: B
                  type: reduce
              - refId: C
                relativeTimeRange:
                  from: 600
                  to: 0
                datasourceUid: __expr__
                model:
                  conditions:
                      - evaluator:
                          params:
                              - 0
                              - 0
                          type: gt
                        operator:
                          type: and
                        query:
                          params: []
                        reducer:
                          params: []
                          type: avg
                        type: query
                  datasource:
                      name: Expression
                      type: __expr__
                      uid: __expr__
                  expression: $B > 0
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: C
                  type: math
            noDataState: OK
            execErrState: Alerting
            for: 10s
            annotations:
              description: |-
                 Pod has been in a non-ready state for longer than 10 minutes.
                 Namespace: {{ "{{" }} $labels.namespace }}
                 Pod: {{ "{{" }} $labels.pod }}
              summary: Kubernetes Pod's probes are failing.
            labels:
              pod_status: prob
            isPaused: false


  contactpoints.yaml: |-
      apiVersion: 1
      contactPoints:
          - orgId: 1
            name: slack
            receivers:
              - name: slack
                uid: my_id_1
                type: slack
                disableResolveMessage: false
                settings:
                  url: https://hooks.slack.com/services/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
                  summary: |
                     {{ `{{ include "default.message" . }}` }}
                  title: |
                     {{ `{{template "slack.title" . }}` }}
                  text: |
                     {{ `{{template "slack.text" .}}` }}
